# Where things are
source:      "."
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling reading
safe:         true
include:      [.htaccess]
exclude:      [Gemfile, Gemfile.lock, README.markdown, Thumbs.db, ehthumbs.db]
keep_files:   []
encoding:     utf-8
markdown_ext: markdown

# Filtering content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: \n\n

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: /typography

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      Europe/Moscow

quiet:    false
defaults:
  -
    scope:
      path: ""
    values:
      author: volado
      lang: ru
      layout: minifier
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post

# Markdown Processors
rdiscount:
  extensions:
    - autolink
    - footnotes
    - generate_toc
    - smart
  toc_token: "[TOC]"

redcarpet:
  extensions:
    - autolink
    - disable_indented_code_blocks
    - fenced_code_blocks
    - footnotes
    - no_intra_emphasis
    - tables
    - with_toc_data

kramdown:
  auto_ids:          false
  #autolink:          true
  enable_coderay:    false
  #footnote_backlink: "&mdash;"
  footnote_nr:       1
  hard_wrap:         false
  input:             GFM
  toc_levels:        2..3

sass:
  sass_dir: _sass
  style: compressed

# Variables
title: Типографика‑ⅩⅪ
url:   https://praepostor.github.io
uuid:  b5eee0e3-51e5-46ad-a7c2-190ecb29a0bd
