# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling reading
safe:         true
include:      [".htaccess"] # Force inclusion in the conversion
exclude:      [] # Exclude from the conversion
keep_files:   [] # When clobbering the site destination, keep the selected files
encoding:     "utf-8"
markdown_ext: "markdown"

# Filtering content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false # Detaches the server from the terminal
port:    4000
host:    127.0.0.1
#baseurl: "/typography" # Does not include hostname
baseurl: "" # Does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      Europe/Moscow

quiet:    false
defaults:
  -
    scope:
      path: ""
    values:
      author: volado
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

sass:
  sass_dir: _sass
  style: compressed

# Variables
title:    "Типографика­‑ⅩⅩⅠ"
url:      "http://localhost:4000"
#url:      "https://praepostor.github.io"
uuid:     "b5eee0e3-51e5-46ad-a7c2-190ecb29a0bd"
