# Where things are
source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts
data_source: ./_data
collections: null

# Handling reading
safe:         true
include:      [".htaccess"] # Force inclusion in the conversion
exclude:      [] # Exclude from the conversion
keep_files:   [] # When clobbering the site destination, keep the selected files
encoding:     "utf-8"
markdown_ext: "markdown,md"

# Filtering content
show_drafts: null
limit_posts: 0
future:      true
unpublished: false

# Plugins
whitelist: []
gems:      []

# Conversion
markdown:    kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

# Serving
detach:  false # Detaches the server from the terminal
port:    4000
host:    127.0.0.1
baseurl: "/typography" # Does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num
timezone:      Europe/Moscow

quiet:    false
defaults:
  -
    scope:
      path: ""
    values:
      author: volado
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: volado
      layout: default
  -
    scope:
      path: _posts/en
    values:
      lang: en
  -
    scope:
      path: _posts/ru
    values:
      lang: ru

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style

# Variables
title:    "Типографика­‑ⅩⅩⅠ"
url:      "http://localhost:4000"
uuid:     "b5eee0e3-51e5-46ad-a7c2-190ecb29a0bd"



home:
  en:
    title: "English"
    url:  "/en/"
  ru:
    title: "Русский"
    url:  "/"

t:
  en:
    home:
      name: "Home1"
      url: "/en"
    fff:
      name: "HomeFen"
      url: "/fffen"
  ru:
    home:
      name: "Дом"
      url: "/"
    fff:
      name: "HomeFru"
      url: "/fffru"
